# Generated by Django 5.0.14 on 2026-05-19 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa Copy'), ('emirates_id', 'Emirates ID')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('manual_review_required', 'Manual Review Required')], default='manual_review_required', max_length=30)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('ocr_confidence', models.FloatField(default=1.0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tickets.ticket')),
            ],
        ),
    ]
