# Generated by Django 5.0.14 on 2026-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa Copy'), ('emirates_id', 'Emirates ID'), ('educational_degree', 'Educational Degree'), ('birth_certificate', 'Birth Certificate'), ('commercial_certificate', 'Commercial Certificate')], max_length=50),
        ),
    ]
